# originals/getting-help-deb-2-8-ui-4260.md: getting-help-838.md
#	chmod 644 originals/*
#	cp getting-help-838.md getting-help-deb-2-8-ui-4260.md
#	xpub pull discourse 4260 4260
#	cp -p getting-help-deb-2-8-ui-4260.md originals
#	rm getting-help-deb-2-8-ui-4260.md
#	chmod 444 originals/*

# originals/getting-help-deb-2-8-cli-4261.md: getting-help-838.md
#	chmod 644 originals/*
#	cp getting-help-838.md getting-help-deb-2-8-cli-4261.md
#	xpub pull discourse 4261 4261
#	cp -p getting-help-deb-2-8-cli-4261.md originals
#	rm getting-help-deb-2-8-cli-4261.md
#	chmod 444 originals/*

# originals/getting-help-deb-2-9-ui-4262.md: getting-help-838.md
#	chmod 644 originals/*
#	cp getting-help-838.md getting-help-deb-2-9-ui-4262.md
#	xpub pull discourse 4262 4262
#	cp -p getting-help-deb-2-9-ui-4262.md originals
#	rm getting-help-deb-2-9-ui-4262.md
#	chmod 444 originals/*

# originals/getting-help-deb-2-9-cli-4263.md: getting-help-838.md
#	chmod 644 originals/*
#	cp getting-help-838.md getting-help-deb-2-9-cli-4263.md
#	xpub pull discourse 4263 4263
#	cp -p getting-help-deb-2-9-cli-4263.md originals
#	rm getting-help-deb-2-9-cli-4263.md
#	chmod 444 originals/*

# originals/getting-help-snap-2-8-ui-4264.md: getting-help-838.md
#	chmod 644 originals/*
#	cp getting-help-838.md getting-help-snap-2-8-ui-4264.md
#	xpub pull discourse 4264 4264
#	cp -p getting-help-snap-2-8-ui-4264.md originals
#	rm getting-help-snap-2-8-ui-4264.md
#	chmod 444 originals/*

# originals/getting-help-snap-2-8-cli-4265.md: getting-help-838.md
#	chmod 644 originals/*
#	cp getting-help-838.md getting-help-snap-2-8-cli-4265.md
#	xpub pull discourse 4265 4265
#	cp -p getting-help-snap-2-8-cli-4265.md originals
#	rm getting-help-snap-2-8-cli-4265.md
#	chmod 444 originals/*

# originals/getting-help-snap-2-9-ui-4266.md: getting-help-838.md
#	chmod 644 originals/*
#	cp getting-help-838.md getting-help-snap-2-9-ui-4266.md
#	xpub pull discourse 4266 4266
#	cp -p getting-help-snap-2-9-ui-4266.md originals
#	rm getting-help-snap-2-9-ui-4266.md
#	chmod 444 originals/*

# originals/getting-help-snap-2-9-cli-4267.md: getting-help-838.md
#	chmod 644 originals/*
#	cp getting-help-838.md getting-help-snap-2-9-cli-4267.md
#	xpub pull discourse 4267 4267
#	cp -p getting-help-snap-2-9-cli-4267.md originals
#	rm getting-help-snap-2-9-cli-4267.md
#	chmod 444 originals/*

# originals/using-maas-in-an-air-gapped-environment-deb-2-8-ui-4268.md: using-maas-in-an-air-gapped-environment-3539.md
#	chmod 644 originals/*
#	cp using-maas-in-an-air-gapped-environment-3539.md using-maas-in-an-air-gapped-environment-deb-2-8-ui-4268.md
#	xpub pull discourse 4268 4268
#	cp -p using-maas-in-an-air-gapped-environment-deb-2-8-ui-4268.md originals
#	rm using-maas-in-an-air-gapped-environment-deb-2-8-ui-4268.md
#	chmod 444 originals/*

# originals/using-maas-in-an-air-gapped-environment-deb-2-8-cli-4269.md: using-maas-in-an-air-gapped-environment-3539.md
#	chmod 644 originals/*
#	cp using-maas-in-an-air-gapped-environment-3539.md using-maas-in-an-air-gapped-environment-deb-2-8-cli-4269.md
#	xpub pull discourse 4269 4269
#	cp -p using-maas-in-an-air-gapped-environment-deb-2-8-cli-4269.md originals
#	rm using-maas-in-an-air-gapped-environment-deb-2-8-cli-4269.md
#	chmod 444 originals/*

# originals/using-maas-in-an-air-gapped-environment-deb-2-9-cli-4270.md: using-maas-in-an-air-gapped-environment-3539.md
#	chmod 644 originals/*
#	cp using-maas-in-an-air-gapped-environment-3539.md using-maas-in-an-air-gapped-environment-deb-2-9-cli-4270.md
#	xpub pull discourse 4270 4270
#	cp -p using-maas-in-an-air-gapped-environment-deb-2-9-cli-4270.md originals
#	rm using-maas-in-an-air-gapped-environment-deb-2-9-cli-4270.md
#	chmod 444 originals/*

# originals/using-maas-in-an-air-gapped-environment-deb-2-9-cli-4270.md: using-maas-in-an-air-gapped-environment-3539.md
#	chmod 644 originals/*
#	cp using-maas-in-an-air-gapped-environment-3539.md using-maas-in-an-air-gapped-environment-deb-2-9-cli-4270.md
#	xpub pull discourse 4270 4270
#	cp -p using-maas-in-an-air-gapped-environment-deb-2-9-cli-4270.md originals
#	rm using-maas-in-an-air-gapped-environment-deb-2-9-cli-4270.md
#	chmod 444 originals/*

# originals/using-maas-in-an-air-gapped-environment-snap-2-8-ui-4271.md: using-maas-in-an-air-gapped-environment-3539.md
#	chmod 644 originals/*
#	cp using-maas-in-an-air-gapped-environment-3539.md using-maas-in-an-air-gapped-environment-snap-2-8-ui-4271.md
#	xpub pull discourse 4271 4271
#	cp -p using-maas-in-an-air-gapped-environment-snap-2-8-ui-4271.md originals
#	rm using-maas-in-an-air-gapped-environment-snap-2-8-ui-4271.md
#	chmod 444 originals/*

# originals/using-maas-in-an-air-gapped-environment-snap-2-8-cli-4272.md: using-maas-in-an-air-gapped-environment-3539.md
#	chmod 644 originals/*
#	cp using-maas-in-an-air-gapped-environment-3539.md using-maas-in-an-air-gapped-environment-snap-2-8-cli-4272.md
#	xpub pull discourse 4272 4272
#	cp -p using-maas-in-an-air-gapped-environment-snap-2-8-cli-4272.md originals
#	rm using-maas-in-an-air-gapped-environment-snap-2-8-cli-4272.md
#	chmod 444 originals/*

# originals/using-maas-in-an-air-gapped-environment-snap-2-9-ui-4273.md: using-maas-in-an-air-gapped-environment-3539.md
#	chmod 644 originals/*
#	cp using-maas-in-an-air-gapped-environment-3539.md using-maas-in-an-air-gapped-environment-snap-2-9-ui-4273.md
#	xpub pull discourse 4273 4273
#	cp -p using-maas-in-an-air-gapped-environment-snap-2-9-ui-4273.md originals
#	rm using-maas-in-an-air-gapped-environment-snap-2-9-ui-4273.md
#	chmod 444 originals/*

# originals/using-maas-in-an-air-gapped-environment-snap-2-9-cli-4274.md: using-maas-in-an-air-gapped-environment-3539.md
#	chmod 644 originals/*
#	cp using-maas-in-an-air-gapped-environment-3539.md using-maas-in-an-air-gapped-environment-snap-2-9-cli-4274.md
#	xpub pull discourse 4274 4274
#	cp -p using-maas-in-an-air-gapped-environment-snap-2-9-cli-4274.md originals
#	rm using-maas-in-an-air-gapped-environment-snap-2-9-cli-4274.md
#	chmod 444 originals/*

# originals/using-maas-in-an-air-gapped-environment-deb-2-9-ui-4275.md: using-maas-in-an-air-gapped-environment-3539.md
#	chmod 644 originals/*
#	cp using-maas-in-an-air-gapped-environment-3539.md using-maas-in-an-air-gapped-environment-deb-2-9-ui-4275.md
#	xpub pull discourse 4275 4275
#	cp -p using-maas-in-an-air-gapped-environment-deb-2-9-ui-4275.md originals
#	rm using-maas-in-an-air-gapped-environment-deb-2-9-ui-4275.md
#	chmod 444 originals/*

# originals/whats-new-in-maas-2-10-4276.md: whats-new-in-maas-2-9-3336.md
#	chmod 644 originals/*
#	cp whats-new-in-maas-2-9-3336.md whats-new-in-maas-2-10-4276.md
#	xpub pull discourse 4276 4276
#	cp -p whats-new-in-maas-2-10-4276.md originals
#	rm whats-new-in-maas-2-10-4276.md
#	chmod 444 originals/*

