#!/bin/bash 
make -f makefile.offline originals/about-maas.html
make -f makefile.offline originals/add-machines.html
make -f makefile.offline originals/adding-a-vm-host.html
make -f makefile.offline originals/api-authentication.html
make -f makefile.offline originals/audit-event-logs.html
make -f makefile.offline originals/availability-zones.html
make -f makefile.offline originals/block-devices.html
make -f makefile.offline originals/cli-advanced-tasks.html
make -f makefile.offline originals/cli-composable-hardware.html
make -f makefile.offline originals/cli-image-management.html
make -f makefile.offline originals/cli-interface-management.html
make -f makefile.offline originals/cli-kernel-management.html
make -f makefile.offline originals/commission-machines.html
make -f makefile.offline originals/commissioning-and-hardware-testing-scripts.html
make -f makefile.offline originals/commissioning-logs.html
make -f makefile.offline originals/common-cli-tasks.html
make -f makefile.offline originals/concepts-and-terms.html
make -f makefile.offline originals/configuration-journey.html
make -f makefile.offline originals/configuring-tls-encryption.html
make -f makefile.offline originals/contact-us.html
make -f makefile.offline originals/controllers.html
make -f makefile.offline originals/creating-a-custom-ubuntu-image.html
make -f makefile.offline originals/creating-and-deleting-vms.html
make -f makefile.offline originals/custom-machine-setup.html
make -f makefile.offline originals/deploy-machines.html
make -f makefile.offline originals/discourse-statistics-1515.html
make -f makefile.offline originals/disk-erasure.html
make -f makefile.offline originals/enabling-maas.html
make -f makefile.offline originals/event-logs-snap-2-7-cli-3382.html
make -f makefile.offline originals/event-logs.html
make -f makefile.offline originals/explore-maas.html
make -f makefile.offline originals/getting-help.html
make -f makefile.offline originals/give-me-an-example-of-maas.html
make -f makefile.offline originals/hardening-your-maas-installation.html
make -f makefile.offline originals/hardware-testing.html
make -f makefile.offline originals/high-availability.html
make -f makefile.offline originals/historical-release-notes-835.html
make -f makefile.offline originals/http-access-log.html
make -f makefile.offline originals/http-error-log.html
make -f makefile.offline originals/images.html
make -f makefile.offline originals/interactive-search.html
make -f makefile.offline originals/ip-ranges.html
make -f makefile.offline originals/ipv6-addressing.html
make -f makefile.offline originals/kernel-boot-options.html
make -f makefile.offline originals/language-details-contributing-to-maas-docs.html
make -f makefile.offline originals/local-image-mirror.html
make -f makefile.offline originals/maas-cli.html
make -f makefile.offline originals/maas-communication.html
make -f makefile.offline originals/maas-documentation-gold-master.html
make -f makefile.offline originals/maas-documentation.html
make -f makefile.offline originals/maas-image-builder.html
make -f makefile.offline originals/maas-installation.html
make -f makefile.offline originals/maas-log-file.html
make -f makefile.offline originals/maas-logging.html
make -f makefile.offline originals/maas-requirements.html
make -f makefile.offline originals/maas-rsyslog-files.html
make -f makefile.offline originals/maas-tags.html
make -f makefile.offline originals/machine-logs.html
make -f makefile.offline originals/machines.html
make -f makefile.offline originals/managing-dhcp.html
make -f makefile.offline originals/managing-stp.html
make -f makefile.offline originals/network-discovery.html
make -f makefile.offline originals/network-testing.html
make -f makefile.offline originals/networking.html
make -f makefile.offline originals/ntp-services.html
make -f makefile.offline originals/package-repositories.html
make -f makefile.offline originals/partitions.html
make -f makefile.offline originals/postgresql-ha-hot-standby.html
make -f makefile.offline originals/power-management.html
make -f makefile.offline originals/prometheus-metrics.html
make -f makefile.offline originals/proxy-log.html
make -f makefile.offline originals/proxy.html
make -f makefile.offline originals/python-api-client.html
make -f makefile.offline originals/rack-controllers.html
make -f makefile.offline originals/region-controllers.html
make -f makefile.offline originals/resource-pools.html
make -f makefile.offline originals/select-and-import-images.html
make -f makefile.offline originals/storage.html
make -f makefile.offline originals/subnet-management.html
make -f makefile.offline originals/test-logs.html
make -f makefile.offline originals/test.html
make -f makefile.offline originals/the-cli-cookbook.html
make -f makefile.offline originals/the-rackd-log-file.html
make -f makefile.offline originals/the-regiond-log-file.html
make -f makefile.offline originals/tips-tricks-and-traps.html
make -f makefile.offline originals/tmp.html
make -f makefile.offline originals/troubleshooting.html
make -f makefile.offline originals/ubuntu-kernels.html
make -f makefile.offline originals/upgrading-maas.html
make -f makefile.offline originals/user-accounts.html
make -f makefile.offline originals/vm-host-networking.html
make -f makefile.offline originals/vm-host-storage-pools.html
make -f makefile.offline originals/vm-hosting.html
make -f makefile.offline originals/vmware-images.html
make -f makefile.offline originals/vmware-vmfs-datastores.html
make -f makefile.offline originals/whats-new-in-maas.html
make -f makefile.offline originals/writing-guide.html
make -f makefile.offline originals/zone-examples.html
