# originals/supported-versions-snap-2-7-ui-4346.md: supported-versions.md
#	chmod 644 originals/*
#	cp supported-versions.md supported-versions-snap-2-7-ui-4346.md
#	xpub pull discourse 4346 4346
#	cp -p supported-versions-snap-2-7-ui-4346.md originals
#	rm supported-versions-snap-2-7-ui-4346.md
#	chmod 444 originals/*

# originals/supported-versions-snap-2-7-cli-4347.md: supported-versions.md
#	chmod 644 originals/*
#	cp supported-versions.md supported-versions-snap-2-7-cli-4347.md
#	xpub pull discourse 4347 4347
#	cp -p supported-versions-snap-2-7-cli-4347.md originals
#	rm supported-versions-snap-2-7-cli-4347.md
#	chmod 444 originals/*

# originals/supported-versions-snap-2-8-ui-4348.md: supported-versions.md
#	chmod 644 originals/*
#	cp supported-versions.md supported-versions-snap-2-8-ui-4348.md
#	xpub pull discourse 4348 4348
#	cp -p supported-versions-snap-2-8-ui-4348.md originals
#	rm supported-versions-snap-2-8-ui-4348.md
#	chmod 444 originals/*

# originals/supported-versions-snap-2-8-cli-4349.md: supported-versions.md
#	chmod 644 originals/*
#	cp supported-versions.md supported-versions-snap-2-8-cli-4349.md
#	xpub pull discourse 4349 4349
#	cp -p supported-versions-snap-2-8-cli-4349.md originals
#	rm supported-versions-snap-2-8-cli-4349.md
#	chmod 444 originals/*

# originals/supported-versions-snap-2-9-ui-4350.md: supported-versions.md
#	chmod 644 originals/*
#	cp supported-versions.md supported-versions-snap-2-9-ui-4350.md
#	xpub pull discourse 4350 4350
#	cp -p supported-versions-snap-2-9-ui-4350.md originals
#	rm supported-versions-snap-2-9-ui-4350.md
#	chmod 444 originals/*

# originals/supported-versions-snap-2-9-cli-4351.md: supported-versions.md
#	chmod 644 originals/*
#	cp supported-versions.md supported-versions-snap-2-9-cli-4351.md
#	xpub pull discourse 4351 4351
#	cp -p supported-versions-snap-2-9-cli-4351.md originals
#	rm supported-versions-snap-2-9-cli-4351.md
#	chmod 444 originals/*

# originals/supported-versions-deb-2-7-ui-4352.md: supported-versions.md
#	chmod 644 originals/*
#	cp supported-versions.md supported-versions-deb-2-7-ui-4352.md
#	xpub pull discourse 4352 4352
#	cp -p supported-versions-deb-2-7-ui-4352.md originals
#	rm supported-versions-deb-2-7-ui-4352.md
#	chmod 444 originals/*

# originals/supported-versions-deb-2-7-cli-4353.md: supported-versions.md
#	chmod 644 originals/*
#	cp supported-versions.md supported-versions-deb-2-7-cli-4353.md
#	xpub pull discourse 4353 4353
#	cp -p supported-versions-deb-2-7-cli-4353.md originals
#	rm supported-versions-deb-2-7-cli-4353.md
#	chmod 444 originals/*

# originals/supported-versions-deb-2-8-ui-4354.md: supported-versions.md
#	chmod 644 originals/*
#	cp supported-versions.md supported-versions-deb-2-8-ui-4354.md
#	xpub pull discourse 4354 4354
#	cp -p supported-versions-deb-2-8-ui-4354.md originals
#	rm supported-versions-deb-2-8-ui-4354.md
#	chmod 444 originals/*

# originals/supported-versions-deb-2-8-cli-4355.md: supported-versions.md
#	chmod 644 originals/*
#	cp supported-versions.md supported-versions-deb-2-8-cli-4355.md
#	xpub pull discourse 4355 4355
#	cp -p supported-versions-deb-2-8-cli-4355.md originals
#	rm supported-versions-deb-2-8-cli-4355.md
#	chmod 444 originals/*

# originals/supported-versions-deb-2-9-ui-4356.md: supported-versions.md
#	chmod 644 originals/*
#	cp supported-versions.md supported-versions-deb-2-9-ui-4356.md
#	xpub pull discourse 4356 4356
#	cp -p supported-versions-deb-2-9-ui-4356.md originals
#	rm supported-versions-deb-2-9-ui-4356.md
#	chmod 444 originals/*

# originals/supported-versions-deb-2-9-cli-4357.md: supported-versions.md
#	chmod 644 originals/*
#	cp supported-versions.md supported-versions-deb-2-9-cli-4357.md
#	xpub pull discourse 4357 4357
#	cp -p supported-versions-deb-2-9-cli-4357.md originals
#	rm supported-versions-deb-2-9-cli-4357.md
#	chmod 444 originals/*

