# originals/using-lxd-projects-with-maas-snap-3-0-ui-4470.md: using-lxd-projects-with-maas.md
#	chmod 644 originals/*
#	cp using-lxd-projects-with-maas.md using-lxd-projects-with-maas-snap-3-0-ui-4470.md
#	xpub pull discourse 4470 4470
#	cp -p using-lxd-projects-with-maas-snap-3-0-ui-4470.md originals
#	rm using-lxd-projects-with-maas-snap-3-0-ui-4470.md
#	chmod 444 originals/*

# originals/using-lxd-projects-with-maas-snap-3-0-cli-4471.md: using-lxd-projects-with-maas.md
#	chmod 644 originals/*
#	cp using-lxd-projects-with-maas.md using-lxd-projects-with-maas-snap-3-0-cli-4471.md
#	xpub pull discourse 4471 4471
#	cp -p using-lxd-projects-with-maas-snap-3-0-cli-4471.md originals
#	rm using-lxd-projects-with-maas-snap-3-0-cli-4471.md
#	chmod 444 originals/*

# originals/using-lxd-projects-with-maas-deb-3-0-cli-4472.md: using-lxd-projects-with-maas.md
#	chmod 644 originals/*
#	cp using-lxd-projects-with-maas.md using-lxd-projects-with-maas-deb-3-0-cli-4472.md
#	xpub pull discourse 4472 4472
#	cp -p using-lxd-projects-with-maas-deb-3-0-cli-4472.md originals
#	rm using-lxd-projects-with-maas-deb-3-0-cli-4472.md
#	chmod 444 originals/*

# originals/using-lxd-projects-with-maas-deb-3-0-ui-4473.md: using-lxd-projects-with-maas.md
#	chmod 644 originals/*
#	cp using-lxd-projects-with-maas.md using-lxd-projects-with-maas-deb-3-0-ui-4473.md
#	xpub pull discourse 4473 4473
#	cp -p using-lxd-projects-with-maas-deb-3-0-ui-4473.md originals
#	rm using-lxd-projects-with-maas-deb-3-0-ui-4473.md
#	chmod 444 originals/*

# originals/tags-and-annotations-draft-document-4500.md: tags-and-annotations.md
#	chmod 644 originals/*
#	cp tags-and-annotations.md tags-and-annotations-draft-document-4500.md
#	xpub pull discourse 4500 4500
#	cp -p tags-and-annotations-draft-document-4500.md originals
#	rm tags-and-annotations-draft-document-4500.md
#	chmod 444 originals/*

# originals/maas-installation-technical-reference-snap-2-7-ui-4518.md: maas-installation-technical-reference.md
#	chmod 644 originals/*
#	cp maas-installation-technical-reference.md maas-installation-technical-reference-snap-2-7-ui-4518.md
#	xpub pull discourse 4518 4518
#	cp -p maas-installation-technical-reference-snap-2-7-ui-4518.md originals
#	rm maas-installation-technical-reference-snap-2-7-ui-4518.md
#	chmod 444 originals/*

